version: '3'
services:
  api-service:
    build: ./MyAPI/
    container_name : myFlaskAPI
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment: 
      PORT: 5000
      FLASK_DEBUG: 1
    restart: always
  front-vuejs:
    build: ./todo-list-front/
    container_name : todoListFront
    ports:
      - 8080:8080
    restart: always