version: '3'
services:
  api-service:
    build: ./MyAPI/
    container_name : myFlaskAPI
    volumes:
      - ./:/app/api
    ports:
      - 5000:5000
    environment: 
      PORT: 5000
      FLASK_DEBUG: 1
    restart: always
  #front-vue:
  #  build: ./todo-list-front/
  #  container_name : todoListFront
  #  volumes:
  #    - ./:/app/my-app
  #  ports:
  #    - 8080:8080
  
  
  #mongodb:
  #  image: mongo:latest
  #  container_name: mongodb
  #  hostname: mongodb
  #  volumes:
  #      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
  #      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
  #      - ./.docker/mongodb/data/db/:/data/db/
  #      - ./.docker/mongodb/data/log/:/var/log/mongodb/
  #  env_file:
  #      - .env
  #  environment:
  #      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  #  ports:
  #      - "27017:27017"
  #  command: ["-f", "/etc/mongod.conf"]